--SJNOS by MC403. web_dns.exe (cu5YT97U)

local tArgs = {...}
local PART_NAME = 'webdns'
local PART_PATH = 'SJNOS/' .. PART_NAME .. '.exe'
local CODE = 'cu5YT97U'

local function start()

if (not os.loadAPI("SJNOS/api/sjn")) then
	error("SJN API missing")
end

local cpos, clear, tcolor, bcolor, getTime = sjn.getStandardFunctions()

local function func_rednet()
	local _, rednetside = sjn.getRednet(true)
	
	while (rednetside == nil) do
		tcolor(colors.red)
		write("No modem found!")
		tcolor(colors.lightGray)
		textutils.slowPrint(" Please put a rednet modem on one side. Press any key to refresh.")
		os.pullEventRaw("key")
		_, rednetside = sjn.getRednet(true)
	end

	return rednetside
end
	
if tArgs[1]=="install" then
	fs.delete(PART_PATH)
	fs.delete("startup")
	fs.move("SJNOS/partinstaller.exe", PART_PATH)
	
	local f = fs.open("startup","w")
	f.writeLine("--Autogenerated Startup by SJNOS")
	f.writeLine('shell.run("'..PART_PATH..' firstrun")')
	f.close()

	local f = fs.open("SJNOS/.installed","w")
	f.close()
elseif tArgs[1]=="firstrun" then
	fs.delete("SJNOS/.installed")

	tcolor(colors.lightGray)
	bcolor(colors.gray)
	clear()
	cpos(1,1)
	textutils.slowPrint("Hello, welcome to 'S-WEB DNS'!")
	print("> Start Setup")
	print("  Deinstall")
	
	local selected = 1
	
	local c = true
	
	while c do
		local event, btn = os.pullEventRaw()
		if (event=="key") then
			if (btn==28) then
				--Enter
				c = false
			elseif (btn==208 or btn==200) then
				--Down or Up
				if (selected==1) then
					selected = 2
				else
					selected = 1
				end
				cpos(1,2)
				print("  Start Setup")
				print("  Deinstall")
				cpos(1,1+selected)
				write(">")
			end
		end
	end
	
	if (selected==2) then
		--Deinstall
		shell.run(PART_PATH, "deinstall")
		return true
	end

	--Setup
	tcolor(colors.lightGray)
	bcolor(colors.gray)
	clear()
	cpos(1,1)

	func_rednet()
	
	clear()
	cpos(1,1)

	local print_reboot_msg = false

	if (not fs.exists("SJNOS/cfg")) then
		fs.makeDir("SJNOS/cfg")
	end

	if (not fs.exists("SJNOS/cfg/server.cfg")) then
		local f = fs.open("SJNOS/cfg/server.cfg","w")
		f.writeLine("welcome=Hello World!")
		f.close()
	else
		tcolor(colors.lime)
		print("Data restored:")
		tcolor(colors.lightGray)
		local data = sjn.getConfigFileContent("SJNOS/cfg/server.cfg", '=')
		print("Your welcome message is " .. data.welcome)
		print_reboot_msg = true
	end
	
	if (not fs.exists("SJNOS/cfg/wfm.cfg")) then
		local f = fs.open("SJNOS/cfg/wfm.cfg", "w")
		f.close()
	end

	fs.makeDir("SJNOS/domains")

	local list = fs.list("SJNOS/domains")
	if (#list > 0) then
		print_reboot_msg = true
		cpos(1, 4)
		tcolor(colors.lime)
		print("Domains restored:")
		tcolor(colors.lightGray)
		for i=1,#list do
			local f = fs.open("SJNOS/domains/"..list[i], "r")
			local d_id = f.readLine()
			f.close()

			cpos(7-#tostring(d_id), 4 + i)
			write(d_id)
			cpos(8, 4 + i)
			write(list[i])
		end
	end

	local f = fs.open("startup","w")
	f.writeLine("--Autogenerated Startup by SJNOS")
	f.writeLine('shell.run("'..PART_PATH..'")')
	f.close()
	
	if (print_reboot_msg) then
		tcolor(colors.yellow)
		textutils.slowPrint("\n\nPress any key to reboot.")
		os.pullEventRaw("key")
	end

	os.reboot()
elseif (tArgs[1] == 'update') then
	bcolor(colors.gray)
	tcolor(colors.lightGray)
	clear()
	cpos(1, 1)
	print("Updating...")
	sleep(1)
	fs.delete("SJNOS/api/sjn")
	shell.run("pastebin get Ab5cy6F2 SJNOS/api/sjn")
	fs.delete(PART_PATH)
	fs.delete("SJNOS/partinstaller.exe")
	shell.run("pastebin", "get", CODE, "SJNOS/partinstaller.exe")
	shell.run("SJNOS/partinstaller.exe install")

	tcolor(colors.lime)
	print("\nSuccess! Starting setup...")
	sleep(1.5)
	os.reboot()
	return true
elseif (tArgs[1] == 'deinstall') then
	tcolor(colors.lightGray)
	bcolor(colors.gray)
	clear()
	local function w(text)
		term.scroll(1)
		cpos(1,19)
		write(text)
	end
	w("Starting Deinstallation...")
	sleep(0.5)
	fs.delete("startup")
	fs.delete("SJNOS")
	tcolor(colors.lime)
	w("Success!")
	tcolor(colors.lightGray)
	w("Exiting...")
	w("Goodbye!")
	sleep(2)
	tcolor(colors.white)
	bcolor(colors.black)
	clear()
	cpos(1, 1)
else
	func_rednet()
	
	local data = sjn.getConfigFileContent("SJNOS/cfg/server.cfg", '=')
	local WELCOME_TEXT = data.welcome
	
	local function save()
		local f = fs.open("SJNOS/cfg/server.cfg","w")
		f.writeLine("welcome="..WELCOME_TEXT)
		f.close()
	end
	
	tcolor(colors.lightGray)
	bcolor(colors.gray)
	clear()
	cpos(1,19)
	print("SJNOS SWEB DNS SERVER #"..os.getComputerID())
	print("Press any key to enter the terminal and enter 'help' for help")
	write("The DNS is listening now and writes a message, if something happends")
	
	
	while true do
		local timer = os.startTimer(10)
		local event, side, channel, id, msg, dis = os.pullEventRaw()
		if (event=="key") then
			local o = true
			while o do
				term.scroll(1)
				cpos(1,19)
				tcolor(colors.orange)
				write("$ ")
				input = read()
				tcolor(colors.lightGray)
				if (input=="help") then
					print("$clear                Clears the screen            ")
					print("$cos                  Goes back to CraftOS         ")
					print("$exit                 Exits the menu               ")
					print("$help                 Shows you some help          ")
					print("$domains              Shows all domains            ")
					print("$remove <NAME>        Deletes an existing domain   ")
					print("$update               Update to the newest version.\n                      Your data will be kept.")
					write("$welcome <MESSAGE>    Text send to other computers \n                      at DNS Request")
				elseif (input=="clear") then
					clear()
				elseif (input=="exit" or input=="" ) then
					o = false
				elseif (input=="domains") then
					local list = fs.list("SJNOS/domains")
					for i=1,#list do
						local f = fs.open("SJNOS/domains/"..list[i], 'r')
						local d_id = f.readLine()
						f.close()

						cpos(7-#tostring(d_id), 19)
						write(d_id)
						cpos(8, 19)
						write(list[i])

						if (i < #list) then
							print()
						end
					end
					print(#list .. ' users in total.')
				elseif (input == 'update') then
					shell.run(PART_PATH, "update")
					return true
				elseif (string.find(input,"remove ")==1) then
					local p1, p2 = string.find(input,"remove ")
					local target = string.sub(input,p2+1)
					if (fs.exists("SJNOS/domains/" .. target)) then
						fs.delete("SJNOS/domains/" .. target)
						write(target .. " has been removed.")
					else
						write(target .. " is not a domain on this server.")
					end
				elseif (input=="cos") then
					return true
				elseif (string.find(input,"welcome ")==1) then
					local p1, p2 = string.find(input,"welcome ")
					local welcome = string.sub(input,p2+1)
					if (#welcome > 20) then
						tcolor(colors.red)
						write("To long! (max=20)")
					else
						tcolor(colors.lightGray)
						write("New message is: ")
						tcolor(colors.yellow)
						write(welcome)
						tcolor(colors.lightGray)
						write(".")
						
						WELCOME_TEXT = welcome
						save()
					end
				elseif (input=="welcome") then
					tcolor(colors.lightGray)
					write("Your welcome message is: ")
					tcolor(colors.yellow)
					write(WELCOME_TEXT)
					tcolor(colors.lightGray)
					write(".")
				else
					tcolor(colors.red)
					write("This Command does not exist!")
				end
			end
		elseif (event=="modem_message") then
			--ID MSG DIS
			if (msg=="~SJN@SWEBSERVER:GETDNSSERVER") then
				sleep(0.5)
				rednet.send(id,"~SJN@SWEBDNS:GETDNSSERVER:TRUE#"..WELCOME_TEXT)
			elseif (msg=="~SJN@SWEBCLIENT:GETDNSSERVER") then
				sleep(0.5)
				rednet.send(id,"~SJN@SWEBDNS:GETDNSSERVER:TRUE#"..WELCOME_TEXT)
			elseif (string.find(msg,"~SJN@SWEBSERVER:CONNECTTODNSSERVER#")==1) then
				--New domain
				local _, p = string.find(msg,"~SJN@SWEBSERVER:CONNECTTODNSSERVER#")
				local domain = ''
				if (#msg > p) then
					domain = string.sub(msg, p + 1)
				end

				if (#domain == 0) then
				elseif (string.find(domain," ")) then
				elseif (string.find(domain,",")) then
				elseif (string.find(domain,"\\")) then
				elseif (string.find(domain,"!")) then
				elseif (string.find(domain,"#")) then
				elseif (string.find(domain,"/")) then
				elseif (string.find(domain,"@")) then
				elseif (string.find(domain,'~')) then
				elseif (#domain > 20) then
				else
					local existingDomains = fs.list("SJNOS/domains")
					local okay = true
					local wasthere = false
					
					for i=1,#existingDomains do
						if (existingDomains[i] == domain) then
							local f = fs.open("SJNOS/domains/" .. existingDomains[i], 'r')
							local d_id = f.readLine()
							f.close()

							if (d_id == tostring(id)) then
								fs.delete("SJNOS/domains/"..existingDomains[i])
								wasthere = true
							else
								okay = false
							end
						end
					end
					
					existingDomains = fs.list("SJNOS/domains")

					if okay then
						sleep(0.1)
						rednet.send(id,"~SJN@SWEBDNS:VALIDDOMAIN")

						local create = true
						for i=1, #existingDomains do
							local old = existingDomains[i]
							local f = fs.open("SJNOS/domains/" .. old, "r")
							local c = f.readLine()
							f.close()

							if (c == id .. "") then
								create = false
								fs.move("SJNOS/domains/" .. old, "SJNOS/domains/".. domain)
								write("\n["..getTime().."]: '"..old.."' renamed to '"..domain.."'.")
								break
							end
						end

						if (create) then
							local f = fs.open("SJNOS/domains/" .. domain, "w")
							f.writeLine(id .. "")
							f.close()

							if (not wasthere) then
								write("\n["..getTime().."]: '"..domain.."' added.")
							end
						end
					else
						rednet.send(id,"~SJN@SWEBDNS:INVALIDDOMAIN")
					end
				end
			elseif (string.find(msg, "~SJN@SWEBSERVER:DISCONNECT")) then
				local existingDomains = fs.list("SJNOS/domains")
				for i=1, #existingDomains do
					local old = existingDomains[i]
					local f = fs.open("SJNOS/domains/" .. old, "r")
					local c = f.readLine()
					f.close()

					if (c == tostring(id)) then
						fs.delete("SJNOS/domains/" .. old)
						write("\n["..getTime().."]: Domain '"..old.."' removed.")
						break
					end
				end

			elseif (string.find(msg,"~SJN@SWEBCLIENT:GETIDOF#")) then
				local p1, p2 = string.find(msg, "~SJN@SWEBCLIENT:GETIDOF#")
				local domain = string.sub(msg, p2 + 1)
				
				local domains = fs.list("SJNOS/domains")
				
				local result = false
				local targetID = -1

				for i=1,#domains do
					if (domain == domains[i]) then
						local f = fs.open("SJNOS/domains/"..domain, "r")
						targetID = f.readLine()
						f.close()
						result = true
						break
					end
				end

				if (result) then
					rednet.send(id,"~SJN@SWEBDNS:IDIS#"..targetID)
				else
					rednet.send(id,"~SJN@SWEBDNS:SERVER_NOT_REGISTERED")
				end
			else
				--Received random message by someone
			end
		elseif (event=="timer") then
			
		end
	end
end


return true
end

local ok, err = pcall(start)
if not ok then
	sjn.drawErrorScreen2(err, 'startup')
end