--SJNOS by MC403. turtle_server.exe (xnVe5jHD)

local tArgs = {...}

local function start()

local function tcolor(color)
	if (term.isColor()) then
		term.setTextColor(color)
	end
end
local function bcolor(color)
	if (term.isColor()) then
		term.setBackgroundColor(color)
	end
end
local function cpos(x, y)
	term.setCursorPos(x, y)
end
local function clear()
	term.clear()
end
local function getTime()
	local a = textutils.formatTime(os.time(),true)
	if #a==4 then
		a = "0"..a
	end
	return a
end
local function getFileContent(path)
	if (fs.exists(path)) then
		local f = fs.open(path, "r")
		local contentArray = {}
		local contentString = ""

		local line = "!"

		while (line ~= nil) do
			line = f.readLine()
			contentArray[#contentArray + 1] = line
		end
		f.close()
		local f = fs.open(path, "r")
		contentString = f.readAll()
		f.close()

		return contentArray, contentString
	end
	return nil
end
local function getConfigFileContent(path, char, alternative)
	if (fs.exists(path)) then
		local array = getFileContent(path)
		local result = {}
		local resultALT = {}
		if (char == nil) then char = "=" end
		for i=1, #array do
			local name = string.sub(array[i], 1, string.find(array[i], char)-1)
			local value = string.sub(array[i], string.find(array[i], char)+1)
			
			result[name] = value
			resultALT[i] = {
				["name"] = name,
				["value"] = value
			}
		end
		if (alternative == true) then
			return resultALT
		end
		return result
	end
	return nil
end
local function getPeripheralSide(p_type)
	local sides = {"left","right","top","bottom","front","back"}
	for i=1,6 do
		if peripheral.isPresent(sides[i]) then
			if peripheral.getType(sides[i])==p_type then
				return sides[i]
			end
		end
	end
	return nil
end
local function getRednet(doOpenRednet)
	local REDNETSIDE = getPeripheralSide("modem")
	local REDNET = (REDNETSIDE ~= nil)
	if (doOpenRednet and REDNET and (not rednet.isOpen(REDNETSIDE))) then
		rednet.open(REDNETSIDE)
	end
	return REDNET, REDNETSIDE
end

if (tArgs[1] == "#install#") then
	fs.delete("SJNOS/partstart.exe")
	fs.delete("startup")
	fs.move("SJNOS/partinstaller.exe","SJNOS/partstart.exe")
	
	local f = fs.open("startup","w")
	f.writeLine("--Autogenerated Startup by SJNOS")
	f.writeLine('shell.run("SJNOS/partstart.exe #firstrun#")')
	f.close()

	local f = fs.open("SJNOS/turtles", "w")
	f.close()
	os.reboot()
elseif (tArgs[1] == "#firstrun#") then
	tcolor(colors.cyan)
	bcolor(colors.white)
	clear()
	cpos(1,1)
	textutils.slowPrint("Hello, welcome to the SJN Turtle Server!")

	print("> Start Setup")
	print("  Deinstall")

	local selected = 1
	while (true) do
		local event, btn = os.pullEventRaw()
		if (event=="key") then
			if (btn==keys.enter) then
				break
			elseif (btn==keys.up or btn==keys.down) then
				cpos(1, 1+selected)
				write(" ")
				if (selected == 1) then
					selected = 2
				else
					selected = 1
				end
				cpos(1, 1+selected)
				write(">")
			end
		end
	end

	if (selected==2) then
		--Deinstall
		tcolor(colors.lightGray)
		bcolor(colors.gray)
		clear()
		local function w(text)
			term.scroll(1)
			cpos(1,19)
			write(text)
		end
		w("Starting Deinstallation...")
		sleep(0.5)
		fs.delete("startup")
		fs.delete("SJNOS")
		tcolor(colors.lime)
		w("Success!")
		tcolor(colors.lightGray)
		w("Exiting...")
		w("Goodbye!")
		sleep(2)
		os.reboot()
	else
		--Setup
		tcolor(colors.cyan)
		bcolor(colors.white)
		clear()
		cpos(1,1)
		
		local REDNETSIDE = nil

		local function refresh()
			local _, p = getRednet(true)
			REDNETSIDE = p
		end
		
		refresh()
		
		while (REDNETSIDE == nil) do
			tcolor(colors.red)
			write("Modem required!")
			tcolor(colors.cyan)
			print(" ANY KEY to refresh, CTRG-T to exit.")
			os.pullEventRaw("key")
			refresh()
		end
		
		tcolor(colors.lime)
		print("Found on "..REDNETSIDE..".\n\n")

		tcolor(colors.cyan)

		write("You need a password for this server. It is used when you want to connect a computer to this server.\n> ")
		local password = read("*")

		write("You need also a key for this server. It is used when a turtle wants to connect with this server.\n> ")
		local key = read("*")

		local f = fs.open("SJNOS/cfg", "w")
		f.writeLine("password="..password)
		f.writeLine("key="..key)
		f.close()

		local f = fs.open("startup", "w")
		f.writeLine("--Autogenerated Startup by SJNOS")
		f.writeLine('shell.run("SJNOS/partstart.exe")')
		f.close()
		
		tcolor(colors.cyan)
		textutils.slowPrint("Rebooting...")
		os.reboot()
	end
end

tcolor(colors.orange)
bcolor(colors.gray)
clear()
cpos(1,1)

local REDNET, REDNETSIDE = getRednet(true)
if (not REDNET) then
	tcolor(colors.red)
	print("You need a wireless modem!")
	print("[Press any key to reboot!]")
	os.pullEventRaw()
	os.reboot()
end

local cfg = getConfigFileContent("SJNOS/cfg")
local PASSWORD, KEY = cfg.password, cfg.key

local turtledata = getConfigFileContent("SJNOS/turtles", nil, true)

tcolor(colors.lightGray)
cpos(1, 19)
print("SJNOS TURTLE SERVER #"..os.getComputerID())
print("Press any key to enter the terminal and enter 'help' for help")
write("The Server is listening now and writes a message, if something happends.")

local running = true

while (running) do
	local event, btn, x, y = os.pullEventRaw()
	if (event == "key") then
		term.scroll(1)
		cpos(1,19)
		tcolor(colors.orange)
		write("$ ")
		input = read()
		tcolor(colors.lightGray)
		if (input=="help") then
			print("$help                 Shows you some help          ")
			print("$clear                Clears the screen            ")
			print("$reboot               Reboots the computer         ")
			print("$list                 Shows the list of turtles    ")
			write("$cos                  Goes back to CraftOS         ")
		elseif (input=="clear") then
			clear()
		elseif (input=="reboot") then
			os.reboot()
		elseif (input=="list") then
			for i=1, #turtledata do
				print("#"..turtledata[i].value.." "..turtledata[i].name)
			end
			tcolor(colors.yellow)
			write("\nYou have "..tostring(#turtledata).." turtles.")
		elseif (input=="cos") then
			running = false
		elseif (input~="") then
			tcolor(colors.red)
			write("This command doesn't exist! Try $help!")
		end
	elseif (event == "rednet_message") then
		local id, msg, dis = btn, x, y
		if (string.find(msg, "~SJN@TURTLETURTLE:CONNECT#") == 1) then
			local _, pos = string.find(msg, "~SJN@TURTLETURTLE:CONNECT#")
			local rest = string.sub(msg, pos + 1)..""

			local pos1, pos2 = string.find(rest, "###")
			if (pos1 ~= nil) then
				local key = string.sub(rest, 1, pos1 - 1)
				local name = string.sub(rest, pos2 + 1)

				if (key == KEY) then
					rednet.send(id, "~SJN@TURTLESERVER:CONNECT")
					write("\n["..getTime().."]: #"..id.." CONNECTED. ("..name..")")

					local f = fs.open("SJNOS/turtles", "r")
					local line = f.readLine()
					f.close()

					local f = fs.open("SJNOS/turtles", "a")
					f.write(name.."="..id)
					f.close()
				else
					write("\n["..getTime().."]: #"..id.." ENTERED WRONG KEY.")
				end
			end
		end
	end
end

tcolor(colors.white)
bcolor(colors.black)
clear()
cpos(1,1)

end
local ok, err = pcall(start)
if (not ok) then
	if (term.isColor()) then
		term.setTextColor(colors.orange)
		term.setBackgroundColor(colors.gray)
	end
	term.clear()
	term.setCursorPos(1,1)
	print("ERROR!")
	print(err)
end